using UnityEngine;

public class TextureManager : MonoBehaviour
{
    [SerializeField] private Material targetMaterial;
    [SerializeField] private Texture2D diffuseTexture;
    [SerializeField] private Texture2D normalMap;

    // Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
// Enhanced texture loading
public void ApplyTextures()
    {
        if (targetMaterial != null)
        {
            targetMaterial.SetTexture("_MainTex", diffuseTexture);
            targetMaterial.SetTexture("_BumpMap", normalMap);
        }
    }

    public void PaintTexel(Texture2D texture, int x, int y, Color color)
    {
        texture.SetPixel(x, y, color);
        texture.Apply();
    }
}
